# -*- coding: utf-8 -*-
"""PyBank2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFjr9cVoxlP7cZMSyWL_QkiTFv4Y40M1

Python Analysis of Budget Data
"""

#Get data
from google.colab import files
uploaded = files.upload()

#Import pandas to wrangle dataframes
import pandas as pd

#Load the dataset
df = pd.read_csv('budget_data.csv')

#Total number of months
total_months = len(df)

# Net total amount of "Profit/Losses" over the entire period
total_profit_losses = df['Profit/Losses'].sum()

# Changes in "Profit/Losses" over the entire period
df['Change'] = df['Profit/Losses'].diff()

# Average of changes in "Profit/Losses"
average_change = df['Change'].mean()

# The greatest increase in profits
greatest_increase = df['Change'].max()
greatest_increase_date = df.loc[df['Change'] == greatest_increase, 'Date'].iloc[0]

# The greatest decrease in profits
greatest_decrease = df['Change'].min()
greatest_decrease_date = df.loc[df['Change'] == greatest_decrease, 'Date'].iloc[0]

# Result
print("Financial Analysis")
print("----------------------------")
print(f"Total Months: {total_months}")
print(f"Total: ${total_profit_losses}")
print(f"Average Change: ${average_change:.2f}")
print(f"Greatest Increase in Profits: {greatest_increase_date} (${int(greatest_increase)})")
print(f"Greatest Decrease in Profits: {greatest_decrease_date} (${int(greatest_decrease)})")

#Export Result
# Define the analysis_text variable with your analysis
analysis_text = (
    f"Financial Analysis\n"
    f"----------------------------\n"
    f"Total Months: {total_months}\n"
    f"Total: ${total_profit_losses}\n"
    f"Average Change: ${average_change:.2f}\n"
    f"Greatest Increase in Profits: {greatest_increase_date} (${int(greatest_increase)})\n"
    f"Greatest Decrease in Profits: {greatest_decrease_date} (${int(greatest_decrease)})\n"
)

# Print the analysis to the terminal
print(analysis_text)

# Save the results to a text file
with open('financial_analysis.txt', 'w') as text_file:
    text_file.write(analysis_text)

# Make sure the filename matches what you've saved
from google.colab import files
files.download('financial_analysis.txt')

